Гашков Максим
kontur-csharper/di pull request #104
Opened 2020-11-30 16:28 UTC by Inree

@fng3r

2020-12-02 12:59 UTC, fng3r requested changes

2020-12-02 12:59 UTC, fng3r commented on TagsCloud/Infrastructure/SetExcludingWordsForm.cs
> +namespace TagsCloud.Infrastructure
UI - это слой приложения, а не инфраструктуры

2020-12-02 12:59 UTC, fng3r commented on TagsCloud/Infrastructure/SetExcludingWordsForm.cs
> +                excludedWords.Add(converter.ConvertWord(word));
унеси эту логику туда, где анализируются слова, иначе это придется в каждом клиенте реализовывать

2020-12-02 12:59 UTC, fng3r commented on TagsCloud/Mainform.cs
> +            container.Resolve<SetExcludingWordsForm>().ShowDialog();
очень странный код со сборкой контейнера, причем какого-то ограниченного, исполняющийся каждый раз при клике на кнопку

2020-12-02 12:59 UTC, fng3r commented on TagsCloud/Mainform.cs
> +            container.Resolve<SetExcludingWordsForm>().ShowDialog();
в контейнер принято регистрировать все и сразу, еще до запуска приложения

2020-12-02 12:59 UTC, fng3r commented on TagsCloud/Program.cs
> +            builder.RegisterInstance(new HashSet<FontStyle> {FontStyle.Regular, FontStyle.Italic, FontStyle.Bold}).AsSelf();
а почему не зарегистрировать инстанс настроек с нужными параметрами сразу?

2020-12-02 12:59 UTC, fng3r commented on TagsCloudTests/WordsCounterTests.cs
> +    }
не хватает тестов на:
- фильтрацию
- нормализацию
- интеграционного теста, как это все работает все вместе при анализе произвольного набора слов
отчасти это проблема того, что это никак не протестировать (или очень сложно это сделать), потому что текущая организация кода этого сделать не позволяет

2020-12-04 12:34 UTC, fng3r requested changes

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +        public IEnumerable<Tag> GetTagsFromWords(IEnumerable<Word> words, Graphics graphics)
а этому методу точно нужно быть публичным?  он разве не юзается только лишь для того, чтобы получить тэги, которые потом сразу отрисовываются

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/TagscloudHandler.cs
> +                )
formatting

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/TagscloudHandler.cs
> +        private readonly IWordsFilter wordsFilter;
фильтров может быть сколько угодно, почему он здесь только один?

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/TagscloudHandler.cs
> +                )
а умел бы фильтр по одному слову фильтровать, можно было бы здесь выстроить удобный пайплайн
```
words
    .Select(w => normalizer.Normalize(w)
    .Where(w => filter.Filter(w));
```

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/Infrastructure/Tag.cs
> +                tagFontSize = 1;
`var fontSize = Math.Max((int) (Font.Size * tagsCloudSizeRatio), 1);`?

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/UI/SetExcludingWordsForm.cs
> +        private readonly BlackListWordsFilter filter;
сделать расширяемым, чтобы можно было использовать несколько фильтров

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/UI/SettingsForm.cs
> +            Text = @"Настройки";
зачем здесь raw string?

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/BlackListWordsFilter.cs
> +        public BlackListWordsFilter(HashSet<string> excludedWords, IWordNormalizer normalizer)
зачем ты принимаешь хэшсет
1) если ты его все равно сначала перетряхиваешь?
2) делаешь хэшсет сам?
в общем случае стоит принимать как можно более общий тип, а возвращать как можно более конкретный
здесь достаточно `IReadOnlyCollection` или вообще `IEnumerable`

2020-12-04 12:34 UTC, fng3r commented on TagsCloudTests/WordNormalizerTests.cs
> +        public void WordNormalizer_TestCases(string word, string expectedResult)
очень говорящее название теста

2020-12-04 12:34 UTC, fng3r commented on TagsCloudTests/WordsAnalizationTests.cs
> +        public void WordsAnalization_TestCases(IEnumerable<string> blackList, IEnumerable<string> words, IEnumerable<string> expectedResult)
аналогично

2020-12-04 12:34 UTC, fng3r commented on TagsCloudTests/TagsCloudDrawerTests.cs
> +        TagsCloudSettings defaultSettings = TagsCloudSettings.DefaultSettings;
specify access modifier explicitly

2020-12-04 12:34 UTC, fng3r commented on TagsCloudTests/WordsAnalizationTests.cs
> +    class WordsAnalizationTests
вроде, тестовый класс не совсем так называется

2020-12-04 12:34 UTC, fng3r commented on TagsCloudTests/TagsCloudDrawerTests.cs
> +        public void GetTagsFromWords_ShouldThrowIfCollectionIsNull()
похоже, что ты хочешь использовать нейминг конвешн `Method_ExpectedResult_StateUnderTest`, но что-то не совсем ему соответствуешь (для всех тестов справедливо, да)

2020-12-04 12:34 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +                var wordFont = new Font(tagsCloudSettings.CurrentFontFamily, word.Weight, tagsCloudSettings.CurrentFontStyle);
у тебя вес определяется (почему-то) просто как кол-во появлений слова в тексте, и здесь ты его никак не преобразуешь
правильно ли я понимаю, что если слово встретилось 1000 раз, то оно отрисуется с размером шрифта 1000?

2020-12-05 06:55 UTC, Inree commented on TagsCloud/App/TagscloudDrawer.cs
> +            layouter.Reset();
Лэйаутер сохраняет предыдущие прямоугольники. Чтобы заново отрисовать картинку без казусов, нужно стереть ему память.

2020-12-06 07:57 UTC, fng3r requested changes

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +                throw new InvalidOperationException($"Incorrect type {fileType}");
а почему операция-то некорректная? некорректен аргумент

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +        private string CutCarriageReturnSymbol(string name)
почему аргумент называется `name`?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +            MicrosoftWord.Application app = new MicrosoftWord.Application();
var?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +                words[i - 1] = CutCarriageReturnSymbol(doc.Paragraphs[i].Range.Text);
`words[i-1] = doc.Paragraphs[i].Range.Text[^1]` или `words[i-1] = doc.Paragraphs[i].Range.Text[^1].Trim('\r')`

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +                words[i - 1] = CutCarriageReturnSymbol(doc.Paragraphs[i].Range.Text);
а вообще это можно переписать гораздо понятней и лаконичней с помощью `Skip` и `Select`

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +        public HashSet<string> AvailableFileTypes { get; } = new HashSet<string>{ "doc", "docx"};
для чего он сделан публичным?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/BlackListWordsFilter.cs
> +        internal readonly HashSet<string> BlackList;
internal - это для тестов? или зачем?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TxtFileReader.cs
> +                throw new InvalidOperationException($"Incorrect type {fileType}");
эта логика дублируется во всех ридерах, стоит с этим что-то  сделать

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +                if (value > 0) width = value <= maxWidth ? value : maxWidth;
а если меньше 0, то просто молча ничего не поменяешь? стоит выбрасывать эксепшн, если значение невалидное

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +                if (value > 0) width = value <= maxWidth ? value : maxWidth;
> width = value <= maxWidth ? value : maxWidth

но ведь это не что иное как min(value, maxWidth)

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +        private readonly int maxWidth = 1920;
почему существуют такие ограничения?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +        private readonly int maxWidth = 1920;
вернее, даже так: почему они существуют, и, если даже на то есть основание, почему они зашиты в этот класс?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
>          public static ImageSize operator *(ImageSize size, double a)
что такое `a`?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +                if (value > 0) height = value <= maxHeight ? value : maxHeight;
same thing

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +            return new ImageSize((int) (size.Width * a), (int) (size.height * a));
почему в одном случае используется свойство, а в другом поле? 😮

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/Palette.cs
>          public Palette(Color primaryColor, Color backgroundColor)
для чего нужен конструктор, если сеттеры все равно открыты и можно использовать object initializer?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/Tag.cs
>                      tagFontSize, Font.Style), tagBounds);
**очень** странное форматирование

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Program.cs
> +            builder.RegisterInstance(new HashSet<IFileReader> {new DocFileReader(), new TxtFileReader()}).AsSelf();
а почему ридеры регаются как хэшсет, какой в этом смысл?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +                words[i - 1] = CutCarriageReturnSymbol(doc.Paragraphs[i].Range.Text);
а почему ты не сплитишь саму строчку по пробелам? что, если там больше одного слова?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/RectanglesLayouter.cs
>          }
почему это nested классы, в этом есть какая-то идея?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +                              - layouterCenterDelta;
wtf

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +            var centerPoint = new PointF((float) tagsCloudSettings.ImageSize.Width / 2,
если аргументы не вмещаются в одну строчку, стоит **все** перенести на отдельную строчку, по одному в каждой

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +                throw new NullReferenceException("Words collection should not be null");
но тут нет никаких слов

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +                    new SolidBrush(tagsCloudSettings.Palette.PrimaryColor),
зачем новая кисть создается на каждую итерацию?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudDrawer.cs
> +            return new Size((int) Math.Ceiling((decimal) floatSize.Width),
так у `Math.Ceiling` же есть перегрузка для `double`, почему здесь нужно кастовать к `decimal`?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudHandler.cs
> +            ITagsCloudDrawer drawer)
:(

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TagscloudHandler.cs
> +            ITagsCloudDrawer drawer)
довольно нелогично принимать слова в констурктор, ведь это не зависимость как таковая, особенно учитывая тот факт, что у тебя все равно есть метод `SetWords`,

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/App/TxtFileReader.cs
> +
?

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/Infrastructure/TagscloudSettings.cs
> +            double cloudToImageScaleRatio)
:((

2020-12-06 07:57 UTC, fng3r commented on TagsCloud/UI/Mainform.cs
> +                tagsCloudHandler.SetWords(fileReader.ReadLines(fileName));
а их точно нужно сетить? почему бы не передавать слова в метод `GetTagCloud`?

2020-12-06 07:57 UTC, fng3r commented on TagsCloudTests/BlackListWordsFilterTests.cs
> +        public void BlacklistWordsFilter_ShouldValidateWords_ThatAreNotInBlackList(IEnumerable<string> blackList,
не совсем корректное название теста, валидируются **все** слова, другое дело, что не все из них валидны

2020-12-06 07:57 UTC, fng3r commented on TagsCloudTests/BlackListWordsFilterTests.cs
> +        [TestCase(new[] {"a", "b", "c", "d", "e", "f"}, new[] {"d", "d", "a", "a", "a", "c", "f"}, new string[0])]
такие кейсы абсолютно нечитабельные, тут куча буков, которые нужно в уме отфильтровать и убедиться в том, что оно совпадает с ождаемым значением

2020-12-06 07:57 UTC, fng3r commented on TagsCloudTests/BlackListWordsFilterTests.cs
> +        [TestCase(new[] {"a", "b", "c", "d", "e", "f"}, new[] {"d", "d", "a", "a", "a", "c", "f"}, new string[0])]
вообще фильтр валидирует одно слово, на одном слове и достаточно тестить

2020-12-06 07:57 UTC, fng3r commented on TagsCloudTests/RectanglesLayouterTests.cs
>              var letterSize = new Size(3, 4);
это тесты лэйаутера, откуда здесь взялись буквы и изображения?

2020-12-06 07:57 UTC, fng3r commented on TagsCloudTests/WordNormalizerTests.cs
> +        public void WordNormalizer_ShouldMakeLower_WordsAsParameters(string word, string expectedResult)
ShouldMakeLower_WordsAsParameters - не распарсил, что это значит

2020-12-06 09:23 UTC, Inree commented on TagsCloud/App/DocFileReader.cs
> +        public HashSet<string> AvailableFileTypes { get; } = new HashSet<string>{ "doc", "docx"};
Чтобы форма могла выдать нужный FileReader под конкретный файл

2020-12-06 09:24 UTC, Inree commented on TagsCloud/App/BlackListWordsFilter.cs
> +        internal readonly HashSet<string> BlackList;
Чтобы SetExcludedWordsForm могла выдать на экран какие слова есть

2020-12-06 09:52 UTC, Inree commented on TagsCloud/Infrastructure/ImageSize.cs
> +                if (value > 0) width = value <= maxWidth ? value : maxWidth;
Эти числа настраиваются пользователем. Вряд ли он захочет видеть исключение.

2020-12-07 08:58 UTC, fng3r commented on TagsCloud/App/BlackListWordsFilter.cs
> +        internal readonly HashSet<string> BlackList;
почему форма не хранит эти данные, раз они ей нужны?

2020-12-07 09:03 UTC, fng3r commented on TagsCloud/App/DocFileReader.cs
> +                    yield return word;
это эквивалентно `doc.Paragraphs .SelectMany(p => p.Range.Text.Trim('\r').Split())`

2020-12-07 09:08 UTC, fng3r commented on TagsCloud/App/FileReader.cs
> +        }
а интерфейс-то куда делся? нужно было реализовать здесь `IFileReader`
следующим образом
```
public IEnumerable<string> ReadWords(string fileName)
{
        var fileType = fileName.Split('.')[^1];
        if (!AvailableFileTypes.Contains(fileType))
            throw new ArgumentException($"Incorrect type {fileType}");

       return ReadWordsInternal(fileName)
},
```
где `ReadWordsInternal` - это `protected abstract IEnumerable<string> ReadWordsInternal(string fileName)`, который нужно реализовать в дочерних классах (имя метода такое просто для примера)

2020-12-07 09:09 UTC, fng3r commented on TagsCloud/App/FileReader.cs
> +        }
вместо этого ты определяешь этот метод, который наследуемый класс обязан дернуть, иначе никакой проверки не случится

2020-12-07 09:11 UTC, fng3r commented on TagsCloud/App/FileReader.cs
> +        }
зачем это нужно в базовом классе? конкретным реализациям лучше знать, как получить список слов, это не стоило сюда выносить, потому что общего у разных форматов мало,

2020-12-07 09:13 UTC, fng3r commented on TagsCloud/App/TxtFileReader.cs
> +                yield return word;
тоже переписать с использованием LINQ

2020-12-07 09:14 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +                    width = value;
до сих пор при значении меньше 0 ты просто по-тихому ничего не сделаешь

2020-12-07 09:15 UTC, fng3r commented on TagsCloud/Infrastructure/ImageSize.cs
> +                    width = value;
хотя здесь стоит сигнализировать вызывающему, что он не прав, и ожидаешь ты сюда значения больше 0

2020-12-07 09:16 UTC, fng3r commented on TagsCloud/TagsCloud.csproj
> +    <PackageReference Include="Bundle.Microsoft.Office.Interop" Version="15.0.4569" />
а там же есть прямо конкретный пакет `Microsoft.Office.Interop.Word`, зачем ты тянешь весь офис?

2020-12-07 10:20 UTC, fng3r approved these changes

2022-11-01 05:48 UTC, closed without merging