Сарапин Илья
kontur-csharper/di pull request #116
Opened 2021-09-23 03:16 UTC by SarapinIT

2021-09-23 07:46 UTC, maracuda requested changes

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/Program.cs
> +                container.Bind<MainForm>().ToSelf().InSingletonScope();
Эта строчка не нужна
Контейнер при наличии всех нужных зависимостей сам соберет форму

Однако в некоторых контейнерах это не так и прилетит исключение, если форма не будет зарегистрирована. О плюсах и минусах такого подхода можешь порассуждать+)

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/Program.cs
> +                    pictureBox.RecreateImage(imageSettings);
Этого здесь быть не должно
Похоже на бизнес-логику внутри конфигурации контейнера
Давай попробуем сделать по-другому

Вспомни что за ошибка здесь была и подумай как по-другому решить, прийди ко мне если сам не сможешь

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/Program.cs
> +                container.Bind<IImageHolder>().ToMethod(ctx => ctx.Kernel.Get<PictureBoxImageHolder>());
Это можно совместить с 37 строкой. У метода Bind есть перегрузка <T1, T2>

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/MainForm.cs
> +        public MainForm(IUiAction[] actions, SettingsManager settingsManager, PictureBoxImageHolder pictureBox, Palette palette)
Давай передадим сюда ImageSettings вместо менеджера, ведь это делает нас менее зависимыми от настроек

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/MainForm.cs
> +        public MainForm(IUiAction[] actions, SettingsManager settingsManager, PictureBoxImageHolder pictureBox, Palette palette)
Кажется палитра здесь не нужна

2021-09-23 07:46 UTC, maracuda commented on FractalPainter/App/Actions/DragonFractalAction.cs
> +            var dragonSettings = dragonSettingsFactory.Invoke();
Раньше при генерации настроек использовался new Random(), сейчас этого аргумента нет
Давай добавим и восстановим логику

Можно делать не Invoke, а просто factory()

2021-09-24 05:01 UTC, SarapinIT commented on FractalPainter/App/Program.cs
> +                container.Bind<MainForm>().ToSelf().InSingletonScope();
Да, я привык к SimpleInjector, там по умолчанию нужно все регистрировать явно.
Собственно плюсы в том что простые классы регистрируются автомагически, проще писать, проще читать конфиг контейнера.
Минусы в том что можно забыть сконфигурировать что-то что действительно надо сконфигурировать, как получилось с DragonSettings

2021-09-24 05:53 UTC, SarapinIT commented on FractalPainter/App/Actions/DragonFractalAction.cs
> +            var dragonSettings = dragonSettingsFactory.Invoke();
Поправил

2021-09-24 05:54 UTC, SarapinIT reviewed
Исправил

2022-11-01 05:48 UTC, closed without merging