Морозов Дмитрий
kontur-csharper/di pull request #122
Opened 2021-12-05 10:52 UTC by libses

@nightluna

2021-12-18 22:23 UTC, Evgeniya1994 requested changes

2021-12-18 22:23 UTC, Evgeniya1994 commented on ConsoleRunner/Program.cs
> +            var g = new Generator();
однобуквенные названия не очень

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Cloud/RandomColoringAlgorithm.cs
> +            var r = new Random();
лучше один раз создать

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Generator.cs
> +    public class Generator
у каждого класса должен быть свой файл

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Generator.cs
> +            var Spiral = new ArchimedeanSpiral(new Point(options.X/2, options.Y/2), options.AngleSpeed, options.LinearSpeed);
название с большой буквы

2021-12-18 22:23 UTC, Evgeniya1994 commented on ConsoleRunner/Program.cs
> +    public class Options : IOptions
нужно вынести в отдельный файл

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Generator.cs
> +        public static void Initialize(ContainerBuilder builder)
так плохо, потому что перед использованием СТАТИЧЕСКОГО класса надо позвать еще какой-то метод, чтобы массив заполнился
лучше сделай метод для каждого случая, либо класс

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Image/ColoredCloudToBitmap.cs
> +            foreach (var r in words)
однобуквенные названия - зло

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Image/ImageFormatterHelper.cs
> +            int j;
инициализируй внутри for
for(var j = 0...

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Core.cs
> +    public class Core
непонятное название

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Core.cs
> +        private IFileReader reader;
можно все поля сделать readonly

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Text/StringPreprocessor.cs
> +        ISillyWordRemover sillyRemover;
модификаторов нет

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2/Text/SillyWordsRemover.cs
> +        public string RemoveSillyWords(string input, ISillyWordSelector selector)
странное название, если учитывать, что он ничего не удаляет, по сути вообще ничего не делает
возможно, лучше было сделать не препроцессор, а просто фильтр

2021-12-18 22:23 UTC, Evgeniya1994 commented on TagCloud2Tests/TestOptions.cs
> +    public class TestOptions : IOptions
а зачем новый класс, почему нельзя использовать старый?

2021-12-19 13:05 UTC, libses commented on TagCloud2Tests/TestOptions.cs
> +    public class TestOptions : IOptions
не хочу, чтобы были лишние зависимости)

2022-11-01 05:47 UTC, closed without merging