Алемасцев Никита
kontur-csharper/di pull request #129
Opened 2021-12-06 16:35 UTC by nikovOne

-Удалил всё лишнее))
-Добавил проекты TagCloudVisualization.csproj, TagCloudVisualizationTests.csproj, ConsoleClient.csproj
-Добавил классы для чтения слов, отбора и обработки слов, составления облака и его отрисовку, а также консольного клиента
-Почти все зависимости вынес в конструкторы (кроме Tag.cs, я не понимаю, что с ним делать), решение собрал в клиенте с помощью AutoFac'a
-В проекте клиента есть исходный файл и картинка с результатом

2021-12-06 16:38 UTC, nikovOne commented
@lamanoff

2021-12-07 16:21 UTC, lamanoff requested changes

2021-12-07 16:21 UTC, lamanoff commented on ConsoleClient/Program.cs
> +            builder.RegisterType<FileReader>().As<IFileReader>();
У autofac есть метод, который автоматически сопоставляет классы с интерфейсами из сборки.

2021-12-07 16:21 UTC, lamanoff commented on TagCloudVisualizationTests/CircularCloudLayouterTests.cs
> +        private static void DrawRectangles(IReadOnlyList<Rectangle> rectangles, Graphics brush)
Приватные методы должны идти после публичных

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/CircularCloudLayouter.cs
> +        private Rectangle MoveToCenter(Rectangle previousRectangle)
Огромный метод 0_0

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/FileReader.cs
> +                words.AddRange(line.Split(separators).Where(word => word.Length > 0));
Можно использовать `string.IsNullOrEmpty()`.

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/Interfaces/IFileReader.cs
> +        IEnumerable<string> GetWordsFromFile(StreamReader reader, char[] separators);
Ридер читает не из файла, а из стрима.

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/Interfaces/IImageGenerator.cs
> +        void SetFont(Font newFont);
А зачем давать возможность изменять цвет, шрифт и размеры?

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/Interfaces/IWordPreparator.cs
> +        public IEnumerable<string> GetPreparedWords(IEnumerable<string> unpreparedWords);
`public` в интерфейсах можно не писать.

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/TagCloudCreator.cs
> +        public TagCloudCreator(IFileReader fileReader, IWordPreparator wordPreparator, ICloudLayouter cloudLayouter,
Когда параметров много, их следует писать в отдельных строках.

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/TagCloudCreator.cs
> +        public void CreateAndSaveCloudFromTo(string inputPath, string outputPath)
В качестве точки расширения, было бы полезнее принимать слова, а возвращать `Bitmap`.

2021-12-07 16:21 UTC, lamanoff commented on TagsCloudVisualization/WordPreparator.cs
> +        private readonly Dictionary<SpeechPart, string> speechPartsDictionary = new()
А зачем их переводить на русский?

2021-12-07 16:23 UTC, nikovOne commented on TagsCloudVisualization/WordPreparator.cs
> +        private readonly Dictionary<SpeechPart, string> speechPartsDictionary = new()
Чтобы библиотека с ними работала. Библиотека DeepMorphy работает с русскими словами. https://github.com/lepeap/DeepMorphy#cтруктура-репозитория

2022-11-01 05:47 UTC, closed without merging