Радкевич Марсель
kontur-csharper/di pull request #130
Opened 2021-12-06 17:40 UTC by SquirrelLeonid

@lamanoff

2021-12-07 14:37 UTC, lamanoff requested changes

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Saving/BitmapSaver.cs
> +        private const string BitmapsDirectory = "layouts";
А давай это всё принимать в конструкторе? Вместе с типом файла.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Saving/BitmapSaver.cs
> +            = Directory.GetParent(Environment.CurrentDirectory)?.Parent?.Parent?.FullName;
А если у нас программа будет лежать просто в папке, то куда он сохранит вывод?)

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Visualization/Drawer.cs
> +        public void DrawCanvasBoundary(Graphics g, Size imgSize)
Лучше не сокращать переменные, где это можно не делать)

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Visualization/Drawer.cs
> +        private readonly List<Color> colors = new List<Color>
А давай настройки и цвета тоже принимать в конструкторе.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Filtering/WordsFilter.cs
> +    public class WordsFilter : IFilter
Если этот фильтр фильтрует по длине, то тогда его следует назвать соответственно.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Filtering/WordsFilter.cs
> +            return words.Where(word => word.Length > 3);
Может количество символов принимать как параметр? Это всё создаёт дополнительные точки расширения.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Preprocessing/WordsPreprocessor.cs
> +    public class WordsPreprocessor
Этот класс вообще нужен?) Кажется, он просто дублирует `ToLowerCasePreprocessor` и не реализует интерфейс препроцессора.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Reading/IReader.cs
> +        IEnumerable<string> ReadWordsFromFile(string pathToFile);
А если мы захоти считать слова не из файла? Тут получается интерфейс ридера, у которого будет всегда только реализация чтения из файла.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Reading/InitialWordFormReader.cs
> +            = Directory.GetParent(Directory.GetCurrentDirectory())?.Parent?.Parent?.FullName;
Не стоит завязываться на структуру файлов из солюшна.

2021-12-07 14:37 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Reading/InitialWordFormReader.cs
> +    public class InitialWordFormReader : IReader
Тут две ответственности у класса, который должен выступать только в роде читальщика из файла. Превращение слов в начальную форму нужно внедрять где-то в общий пайплайн обработки. Это своего рода тоже препроцессор.

2021-12-09 14:56 UTC, lamanoff requested changes

2021-12-09 14:56 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Reading/IWordsReader.cs
> +        IEnumerable<string> ReadFromFile(string pathToFile, Encoding encoding);
Можно ли как-то унифицировать ридер? Чтобы он принимал, например, стрим, и не был привязан к способу чтения?

2021-12-09 14:56 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Writing/IWordsWriter.cs
> +    public interface IWordsWriter
Также как-то бы унифицировать райтер, например, писать в стрим, который уже будет писать в файл или консоль.

2021-12-09 14:56 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Words/Writing/ToConsole/ConsoleWriter.cs
> +            foreach (var item in linesToWrite) Console.WriteLine(item);
Инструкцию под циклом следует переносить на новую строку.

2021-12-10 16:56 UTC, SquirrelLeonid commented on TagCloudContainerTask/TagCloud/Saving/BitmapSaver.cs
> +        private const string BitmapsDirectory = "layouts";
Убрал все статические поля из класса.
Эти данные теперь передаются напрямую в метод

2021-12-11 09:00 UTC, lamanoff requested changes

2021-12-11 09:00 UTC, lamanoff commented on TagCloudContainerTask/FileInteractions/Savers/BitmapSaver.cs
> +        public void SaveBitmapTo(
Тоже похоже на статический метод.

2021-12-11 09:00 UTC, lamanoff commented on TagCloudContainerTask/TagCloud/Visualization/Drawer.cs
> +                    new Font("times new roman", tag.WordEmSize),
Шрифт лучше принимать где-то в конструкторе.

2021-12-11 16:12 UTC, SquirrelLeonid commented on TagCloudContainerTask/FileInteractions/Savers/BitmapSaver.cs
> +        public void SaveBitmapTo(
Этот метод идет из интерфейса и не может быть статичным

2022-11-01 05:47 UTC, closed without merging