Полянский Ярослав
kontur-csharper/di pull request #151
Opened 2022-12-04 08:36 UTC by Yaroslav332

@Danko19

2022-12-05 14:28 UTC, Danko19 requested changes

2022-12-05 14:28 UTC, Danko19 commented on TagsCloudContainer/DefaultImageDrawer.cs
> +    public Bitmap DrawnBitmap { get; private set; }
Почему решил сделать свойством а не методом?

2022-12-05 14:28 UTC, Danko19 commented on TagsCloudContainer/DefaultImageDrawer.cs
> +    public Bitmap DrawnBitmap { get; private set; }
Подобный выбор повторяется и в других местах по проекту. Почему бы не добавить в интерфейс метод `DrawImage()` и вызывать его когда надо? 

Прятать потенциально дорогие (по времени выполнения) операции в свойства или конструкторы не очень хороший паттерн, это может быть неочевидно для того, кто будет модифицировать твой код - почему вызов конструктора или свойства тупит несколько секунд? Для метода такое поведение кажется куда более предсказуемым и ожидаемым

2022-12-05 14:28 UTC, Danko19 commented on TagsCloudContainer/WordsFromFileReader.cs
> +public class WordsFromFileReader : IEnumerable<string>
Не совсем понял, для чего нужен этот чувак

2022-12-05 14:28 UTC, Danko19 commented on TagsCloudContainer/WordsHandlerWithFilter.cs
> +        DefaultWordsHandler d = new DefaultWordsHandler(wordSequence);
Напрашивается наследование

2022-12-12 08:04 UTC, Danko19 requested changes

2022-12-12 08:04 UTC, Danko19 commented on TagsCloudContainer/Colorers/IColorer.cs
> +public interface IColorer
`IColorer` как-то режет слух, можно обозвать `IColorProvider` например

2022-12-12 08:04 UTC, Danko19 commented on TagsCloudContainer/Colorers/RandomColorer.cs
> +        var r = new Random();
Объект `Random` хранит внутри себя состояние для генерации равномерного распределения случайных чисел, поэтому его лучше сделать полем класса, а не создавать каждый раз новый

2022-12-12 08:04 UTC, Danko19 commented on TagsCloudContainer/WordsHandlerWithFilter.cs
> +    public Dictionary<string, int> WordDistribution
Странно что мы снова определяем тоже свойство, зачем тогда наследование? Чтобы переприсвоить `WordDistribution` можно у свойства базового класса сделать `protected` setter. Либо сделать так, чтобы `ProcessSequence` возвращал `wordDistribution` и присваивать его в базовом getter-е. Второй вариант мне нравится чуть больше

2022-12-12 08:04 UTC, Danko19 commented on TagsCloudWinformsApp/MainForm.cs
> +        switch (wordColoring_comboBox.SelectedIndex)
Давай заведём массивчик типов, чтобы вместо switch-а, просто брать по индексу

2022-12-12 08:04 UTC, Danko19 commented on TagsCloudWinformsApp/MainForm.cs
> +        switch (layout_comboBox.SelectedIndex)
Аналогично

2022-12-12 08:09 UTC, Danko19 commented
А ещё совсем нет тестов 👉👈
Давай добавим хотя бы несколько, на основные классы с логикой

2022-12-17 08:54 UTC, Yaroslav332 commented
@bannikovilea

2022-12-19 03:39 UTC, bannikovilea commented on TagsCloudContainer/DefaultWordsHandler.cs
> +            if (wordDistribution == null) ProcessSequence();
Очень тяжело смотрится, выглядит как будто после ифа идёт ретур, но там на самом деле метод есть. Давай добавим перенос строки)

2023-11-23 04:57 UTC, closed without merging