Глазунов Никита
kontur-csharper/di pull request #168
Opened 2022-12-07 17:57 UTC by GlazProject

@desolver, посмотри пожалуйста

2022-12-08 13:28 UTC, desolver commented on FractalPainter/fractalPainter.csproj
> +        <TargetFramework>net48</TargetFramework>
ой ей, а это зачем так? на net48 уже никто новые проекты не создает)

2022-12-08 13:28 UTC, desolver commented on TagsCloudVisualisation/TagsCloudVisualisation/TagsCloudVisualisation.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
Аналогично и тут, давай создавать проекты на net core (3.1 как было уже или если хочешь один из самых последних то net6)

2022-12-08 13:28 UTC, desolver commented on TagsCloudVisualisation/TagsCloudVisualisation/Tests/CloudLayouter/SpiralCloudLayouter/CircularCloudLayouterTest.cs
> +namespace TagsCloudVisualisation.Tests.CloudLayouter.SpiralCloudLayouter
Хорошей практикой считается разделение основного кода и тестов на 2 проекта, так тесты не нагружают основной проект собой и могут запускаться отдельно. Давай сделаем так же, соответственно и все зависимости тестов должны жить только в отдельном проекте (проекты тоже на net core создавай, net48 уже давно устарел)

2022-12-08 13:32 UTC, GlazProject commented on FractalPainter/fractalPainter.csproj
> +        <TargetFramework>net48</TargetFramework>
Это FractalPainter. Задание с практики, просто чтобы запускалось, перевёл на 48, потому что 3.1 у меня не стоит

2022-12-10 16:40 UTC, desolver requested changes

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +            //return TextRenderer.MeasureText(word.Value, visualisation.GetFont());
Если будешь делать не консольный клиент, а на формах, допустим, там должен быть (то есть фреймворк будет не просто net 6, а windows-net 6)
https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.textrenderer?view=windowsdesktop-7.0#remarks

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +    /// </summary>
Общий коммент насчет таких комментариев:

1. Да, безусловно это упрощает понимание кода, т.к. автор явно пишет о том, как работает этот код, его тонкости и все такое
2. Круто, что ты попрактиковался в этом в практике, получилось очень хорошо, описывать свой код так понятно тоже надо уметь :)
3. НО это усложняет поддержку твоего кода, т.к. при изменении кода нужно не забывать менять комментарии (ты, как добропорядочный программист, будешь следить за своим кодом и всегда править комментарии после изменений в нем, но не забывай, что этот код будешь писать и править не только ты, и рано или поздно кто-нибудь не поправит коммент, и тогда он будет приносить только боль)
4. Что тогда делать? Писать понятный код :) И понятно называть сущности - у тебя с этим проблем нет, из того что я вижу в этой практике - код прекрасно бы читался и без них
5. ИМХО, комментариями можно покрывать только какие-то полезные утилиты в коде и то только тогда, когда их поведение неочевидно из написанного в них кода. Такие модули - утилиты редко меняются и твои комментарии по их неочевидному поведению могут помочь в будущем тем, кто будет с ними работать
6. В командах Контура комментарии встречаются редко, поэтому не привыкай их писать)

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/CloudLayouter/SpiralCloudLayouters/CircularCloudLayouterTest.cs
> +            var a = TestContext.CurrentContext;
Что такое `a`?)

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/CloudLayouter/SpiralCloudLayouters/CircularCloudLayouterTest.cs
> +    [TestFixture]
`[TestFixture]` можно не писать - если в классе есть методы, помеченные атрибутом `[Test]`, дотнет сам поймет, что это класс для тестов

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/CloudLayouter/SpiralCloudLayouters/Infrastructure/TagCloudDrawer.cs
> +            var g = Graphics.FromImage(myBitmap);
Настолько сильно сокращать нехорошо, слово `graphics` занимает не так много места

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/CloudLayouter/SpiralCloudLayouters/Infrastructure/TagCloudDrawer.cs
> +            bool drawCenter = false, bool drawCircle = false)
Оооочень большое количество параметров в методе. Общая рекомендация - количество параметров не должно превышать 5 штук (и это прям максимум), если больше - надо или дробить метод, или выносить параметры в модель, и в сам метод передавать именно модель `настроек` или `контекст`

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/FileInputStream/FromFileInputWordsStreamTest.cs
> +            Action _ = () =>
А почему название не дал? (тут и в методах ниже)

2022-12-10 16:40 UTC, desolver commented on TagCloudTest/FileInputStream/FromFileInputWordsStreamTest.cs
> +                s => s.Split('\n'));
`\n` это только для windows платформы, на линуксе используется `\r\n`, чтобы всегда это не держать в голове просто используй `Environment.NewLine`

2022-12-10 16:40 UTC, desolver commented on TagsCloudVisualisation/TagsCloudVisualisation/App.config
> +﻿<?xml version="1.0" encoding="utf-8"?><configuration>
Осталось от net48 фреймворка кажется

2022-12-10 16:40 UTC, desolver commented on TagsCloudVisualisation/TagsCloudVisualisation/TagsCloudVisualisation.csproj
> +﻿<?xml version="1.0" encoding="utf-8"?>
И это)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +            ICloudDrawer cloudDrawer)
Зависимости прокидывать в метод как-то не круто, можно ведь спокойно вынести их в конструктор, тогда контейнер создаст и прокинет их за тебя

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +namespace TagCloud.App.CloudCreatorDriver.CloudCreator
Неймспейс получился несколько громоздким, давай попробуем что-нибудь покороче, а то в коде ниже есть и такое )) `TagCloud.App.WordPreprocessorDriver.InputStream.FileInputStream.Exceptions`

Папки лучше называть максимально абстрактно по той доменной области, в которой пишется код в этой папке

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/FromFileInputWordsStream.cs
> +            SelectFile(filename);
1. Проблема производительности - представь, если мы создадим класс, но потом никогда не обратимся к методу `Next`, для чего мы тогда в конструкторе читали этот файл и тратили процессорное время?
2. Но проблема кажется отпадает, потому что конструктор не используется в реальном коде - зачем он тут тогда, как и конструктор выше?

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/FromFileInputWordsStream.cs
> +        public FromFileInputWordsStream(IFileEncoder fileEncoder, Func<string, IEnumerable<string>> splitter)
Не используемый конструктор

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/FromFileInputWordsStream.cs
> +            return splitter(text).Where(s => s.Length > 0).ToList();
Кажется, что splitter не должен быть Func, который прокидывается в конструктор или метод, он должен быть полноценной зависимостью, которая будет уметь сплитить текст на слова

2022-12-10 16:40 UTC, desolver commented on TagCloud/Clients/ConsoleClient/ConsoleClient.cs
> +                    var v = new WordVisualisation(wordColor, 0, new Font("Arial", 3));
Не используется

2022-12-10 16:40 UTC, desolver commented on TagCloud/Clients/ConsoleClient/ConsoleClient.cs
> +                if (GotFilePath(out path)
Методы, возвращающие bool, должны начинаться на `Try, Check, Has, Have, Does, Is` и тд. Тем более тут ты используешь паттерн `Try - out`, который ниже используешь при сохранении картинок. Короче, нужен Try в названии методов)

2022-12-10 16:40 UTC, desolver commented on TagCloud/Clients/ConsoleClient/ConsoleClient.cs
> +                    inputWordsStream.SelectFile(path);
Проблема - вот этой зависимостью можно воспользоваться неправильно, а что если я не выберу файл сначала, а сразу сделаю `Next`, он ведь не инициализирован даже ничем, программа упадет. Такого быть не должно

2022-12-10 16:40 UTC, desolver commented on TagCloud/Program.cs
> +{
Не знаю, подсвечивает ли это студия, но райдер подсказывает о том, что в C# 10 появилась возможность делать file-scoped неймспейсы, то есть неймспейс не будет создавать под собой пару фигурных скобок. Это очень помогает упростить вложенность, возьми на заметку)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/WordsPreprocessor/Word/IWord.cs
> +        public double Tf { get; set; }
`public` в интерфейсах можно не писать, методы и свойства при реализации и так будут публичными

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/WordsPreprocessor/IWordsPreprocessor.cs
> +        ISet<Word.Word> GetProcessedWords(List<string> words, IReadOnlyCollection<IBoringWords> boringWords);
Чтобы избегать `Word.Word` не называй папки и классы в них одинаково)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/WordsPreprocessor/DefaultWordsPreprocessor.cs
> +            foreach (var word in words.Select(wordValue => new Word.Word(wordPreprocessor(wordValue))))
Не очень понял, для чего прокидывать func для `wordPreprocessor`, можно ведь логику прямо тут написать и избавиться от лишнего параметра в методе (используется он только в одном месте) - чем проще код, тем лучше) Если надо будет в будущем кому-нибудь делать разных процессинг слов, пусть придумывают и выносят логику, а пока надо делать максимально просто, как говорится YAGNI )

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/Exceptions/IncorrectFileTypeException.cs
> +    public class IncorrectFileTypeException : Exception
Не очень понял, зачем нужно создавать кастомные классы ошибок, они внутри не реализуют никакую логику. Не усложняй код, просто кидай стандартные типы ошибок, но пиши в них текстом понятный мессадж, который тебе нужен (тут и в других местах)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/RectanglesLayouters/ICloudLayouter.cs
> +        void SetSettings(ICloudLayouterSettings settings);
`SetSettings` выглядит как потенциально опасное место, которое я могу вызвать в любой момент выполнения программы и все сломать. Возможно я не прав

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/ImageSaver/PngImageSaver.cs
> +        }
А зачем? Я так понимаю если получилось созранить  - вернули true, не получилось - false, и не важно какая ошибка произошла. Сделай просто в catch (Exception)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/DrawingSettings/IDrawingSettings.cs
> +        public List<IWordVisualisation> Visualisation { get; }
Публичные листы, эх, сколько же возможностей сломать программу) Программа готова к тому, что в любой момент где-нибудь может произойти вызов `Visualization[0] = null`?

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudDrawers/CloudDrawer.cs
> +            var myBitmap = new Bitmap(width, height);
Bitmap кажется имеет интерфейс `IDisposable`, не забудь освободить ресурсы)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/ImageSaver/FileTypes/IFileType.cs
> +    public interface IFileType
Выглядит как интерфейс ради интерфейса) Используется в одном месте, зачем целый интерфейс и класс просто для того, чтобы передать путь в метод?)

2022-12-10 16:40 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +            while (inputWordsStream.Next())
1. В продакшн коде я бы очень сильно засомневался, увидев такой код - очень похоже на `while (true)` - где гарантия, что мы тут не уйдем в бесконечный цикл?
2. Идея пословного чтения как будто развита не до конца - в итоге мы ведь все равно просто читаем все слова и складываем их в лист, а потом все-все слова фильтруем и обрабатываем (получается несколько раз бегаем по списку слов). Зачем тогда  метод `Next()`? Давай просто вернем все слова из splitter`a и всё, тогда и от этой идеи пословного чтения можно будет избавиться

2022-12-11 04:54 UTC, GlazProject commented on TagCloudTest/FileInputStream/FromFileInputWordsStreamTest.cs
> +            Action _ = () =>
Потому что перепутал, когда нужно называть нижним подчерком, а когда давать нормальное название. Один из предыдущих наставников научил, что если мы создаём вот такое тестовое действие только ради действия, всю его внутреннюю инициализацию можно/нужно называть _, а я протащил это чуть дальше. Всё исправил

2022-12-11 05:17 UTC, GlazProject commented on TagsCloudVisualisation/TagsCloudVisualisation/App.config
> +﻿<?xml version="1.0" encoding="utf-8"?><configuration>
Да, правда. Это я удалил проект из решения, а райдер решил просто снять индексацию, а не удалять файлы. Теперь это всё удалено

2022-12-11 05:24 UTC, GlazProject commented on TagCloud/Clients/ConsoleClient/ConsoleClient.cs
> +                    inputWordsStream.SelectFile(path);
Да, программа упадёт, если не указать путь, но зато с красивой ошибкой )
Попробую переделать так, чтобы получение слов и выбор файла были параметрами одного метода

2022-12-11 05:28 UTC, GlazProject commented on TagCloud/Program.cs
> +{
Я пишу в райдере. Он у меня не подсвечивает это как ошибку, просто фигурную скобку рисует серым, поэтому не заметил, пока не обратил внимание специально. Так непривычно стал выглядеть код

2022-12-11 05:36 UTC, GlazProject commented on TagCloud/App/WordPreprocessorDriver/WordsPreprocessor/DefaultWordsPreprocessor.cs
> +            foreach (var word in words.Select(wordValue => new Word.Word(wordPreprocessor(wordValue))))
Да, согласен. При написании думал, что будут различные способы предварительной подготовки каждого слова по отдельности. Допустим не только привести к нижнему регистру, то и, например, привести к начальной форме. Поэтому такую функциональность заложил. Но тогда нужно делать не функцию, а список каких-нибудь `IWordHandler` или что-то подобное. Но здесь пока это лучше выпилить

2022-12-11 05:40 UTC, GlazProject commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/Exceptions/IncorrectFileTypeException.cs
> +    public class IncorrectFileTypeException : Exception
Нам в блоке про обработку ошибок про это ничего не говорили, поэтому я решил, что свои маркированные ошибки - это хорошо. Сразу покажут, что упало, и помогут обработать такие случаи. 

_P.s я их уберу, потому что в следующей задаче нужно будет как раз каждый метод перевести на возвращение Result :)_

2022-12-11 05:50 UTC, GlazProject commented on TagCloud/App/CloudCreatorDriver/ImageSaver/PngImageSaver.cs
> +        }
Хорошо. Я думал, что если что-то критическое, то лучше пробрасывать выше. Но получается он как самостоятельный модуль может просто сказать "не повезло, не фортануло, не смог я сохранить"
Исправил

2022-12-11 05:52 UTC, GlazProject commented on TagCloud/App/CloudCreatorDriver/DrawingSettings/IDrawingSettings.cs
> +        public List<IWordVisualisation> Visualisation { get; }
Я знаю про такую проблему любых публичных ссылочных типов :(
Тогда напишу полноценные методы добавления и получения данных из этого листа

2022-12-11 05:55 UTC, GlazProject commented on TagCloud/App/CloudCreatorDriver/ImageSaver/FileTypes/IFileType.cs
> +    public interface IFileType
Интерфейс я уберу, а вот класс хотел оставить, чтобы явно заставить программиста задуматься, что здесь нужен путь к файлу, а не просто какая-то строка. На сколько это оправдано?

2022-12-11 05:55 UTC, GlazProject commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +            while (inputWordsStream.Next())
Да, согласен. Тогда сразу в этот метод и будем передавать путь к файлу, из которого читать.

2022-12-11 15:46 UTC, desolver requested changes

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/WordsPreprocessor/Words/IWord.cs
> +    Size MeasureWord(Font font);
Точно ли MeasureWord должен быть внутри реализации? А не снаружи, как экстеншн?

2022-12-11 15:46 UTC, desolver commented on TagCloud/Program.cs
> +{
После старого формата выглядит непривычно, это да) Но когда привыкаешь, начинаешь не то что новый код писать с ними, но ещё и старый переделывать))

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/ImageSaver/FileTypes/IFileType.cs
> +    public interface IFileType
Нуууу спорный вопрос, а кто мешает ему в этот класс передать кривой путь? По идее правильное название переменной в методе несет столько же смысла, сколько и и класс-обертка с правильным названием, а сломать их можно одинаково

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/CloudCreatorDriver/CloudCreator/CloudCreator.cs
> +        this.drawingSettings = drawingSettings ?? throw new ArgumentNullException(nameof(drawingSettings));
Выглядит страшновато, на самом деле можно оставить и без выброса ошибок. Почему? Потому что при создании этой зависимости, если какой-то из них не будет в контейнере, то ошибка упадет сама с текстом о том, что какая-то зависимость класса `CloudCreator` не зарегистрирована. Поэтому мы всё-таки можем быть уверены, что если мы зашли в конструктор, то контейнер собран правильно

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/Exceptions/IncorrectFileTypeException.cs
> +    public class IncorrectFileTypeException : Exception
Ошибок не напасешься на все случаи в коде) В практике очень редко встречаю кастомные ошибки, большинство случае покрывают стандартные

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/FromFileInputWordsStream.cs
> +    public List<string> GetAllWordsFromStream(IStreamContext streamContext, ITextSplitter textSplitter)
Не прокидывай зависимости в методы, интерфейсы в контейнере созданы для того, чтобы их создавать в конструкторе как зависимости класса

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/FileInputStream/FromFileInputWordsStream.cs
> +        if (streamContext is not FromFileStreamContext fileStreamContext)
1. Тут получилось как-то неоднозначно, вроде бы ввели интерфейсы, чтобы уйти от конкретных реализаций, а в итоге проверяем интерфейс на конкретную реализацию)
2. Может быть уйти от интерфейса IStreamContext? А метод будет принимать в параметре FromFileStreamContext, с которым собственно и должен работать

2022-12-11 15:46 UTC, desolver commented on TagCloud/App/WordPreprocessorDriver/InputStream/IStreamContext.cs
> +public interface IStreamContext
Выше писал, что скорее всего интерфейс будет не нужен

2023-11-23 04:57 UTC, closed without merging