 Щапова Мария
kontur-csharper/di pull request #173
Opened 2022-12-07 23:41 UTC by massshasch

@HELLoWorlD01100

2022-12-10 11:22 UTC, HELLoWorlD01100 requested changes
1. Зачем-то выносишь в поля данные, которые будут использоваться ПРИ КАЖДОМ вызове ОПРЕДЕЛЕННОГО метода. Из-за этого для других данных нужно будет создавать еще один класс. 
2. Добавить обработку критичных ситуаций(не найден файл, такого цвета нет и тд).
3. Почему решила писать на framework? Технология достаточно старая и используется только в legacy. К тому же, он медленнее.
4. Не во всех параметрах есть shortname.
5. Чтобы добавить GUI в текущей реализации нужно будет переписывать код.
6. Нету точки расширение по раскраске слов.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            var res = new Dictionary<string, int>();
Буквы пока бесплатные

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/ConsoleUI.cs
> +        [Option("brushcolor", Required = false, Default = "Blue", HelpText = "Brush color")]
А тут почему не пишем shortname?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CustomSettings.cs
> +    public class CustomSettings
А вот если бы использовала последние версии .net, можно было бы использовать [record](https://learn.microsoft.com/ru-ru/dotnet/csharp/language-reference/builtin-types/record)

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        public TxtOpener(CustomSettings settings) => FilePath = settings.PathToOpen;
Зачем знать обо всех настройках?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        private string FilePath { get; }
На каждый путь придётся создавать свой объект

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        private string FilePath { get; }
Нарушение именования приватных членов класса.
Для приватных членов используем readonly, а не get-only

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        public string OpenFile() => File.ReadAllText(FilePath);
Тут же вычитывание из файла происходит. Под капотом мы конечно откроем файл, но это не так важно.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileSavers/IFileSaver.cs
> +        public void SaveCanvas();
Почему просто не передать параметры сразу в метод?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/FileSavers/PNGSaver.cs
> +        public void SaveCanvas() => Canvas.Save(Path, new ImageFormat(ImageFormat.Png.Guid));
У меня кстати не сохранилось с нужным форматом. 
Для Unix - систем это не страшно, 
А вот для windows это не самое приятное

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +            return input.Split(new[] {'\n', ' '});
\n это вот у вас на маках.
У четких парней на винде \r\n

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +            builder.RegisterType<TxtOpener>().As<IFileOpener>();
Ок, а как другой IFileOpener добавлять будем?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +            builder.RegisterInstance(new CustomSettings(parsedArguments.FontName,
А если у нас GUI?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +            var builder = new ContainerBuilder();
Мб вынести регистрацию зависимостей в отдельный метод?

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +        public DefaultStainer(InputFileHandler handler, CustomSettings settings)
Непонятно что делает класс. Очень абстрактные названия, придётся код читать :(

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +            StartColor = Color.FromName(settings.BrushColor);
Если я укажу несуществующий цвет, то вообще ничего не отрисуется))

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CicularCloudDrawer.cs
> +    public class CircularCloudDrawer
А логика для рисовки отличается +- только алгоритмом. Зачем нам каждый раз писать отдельный класс для этого? 
Нарушение полиморфизма.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CoefficientCalculator.cs
> +    public class CoefficientCalculator
Очень абстрактное название, мне пришлось читать код, чтобы понять, что происходит

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +        private Dictionary<string, int> MakeWordsFrequencyDictionary(string[] words)
Пользуйся принципом:
Метод принимает наименьшую возможную реализацию, нужную для работы метода, а возвращает как можно более подробную реализацию. 
Я могу захотеть отдать в этот метод List<T>, но мне придётся его дополнительно приводить к массиву.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +            for (int i = 0; i < WordsCount; i++)
var

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Tests/RectangleCoordinatesCalculatorTests.cs
> +/*using System;
Вынести тесты в отдельный проект.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            foreach (var pair in words)
можно сразу получить key и value

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
В публичных методах кортежи лучше не использовать, т.к менее понятно что это вообще.

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
А зачем нам знать возвращаемый тип в имени метода?)

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
Почему у нас класс, который раскладывает прямоугольники, теперь что-то знает про коэф. размера, которые нужны, чтобы получилось нормально изображение, знает про слова и знает еще кучу всего, чего знать не должен. К тому же нам всю эту логику нужно будет обязательно продублировать во всех алгоритмах.
Логика расплылась + нарушение полиморфизма. Что нам мешает извне это всё делать?(работа со словами)

2022-12-10 11:22 UTC, HELLoWorlD01100 commented on TagsCloudContainer/BoringWordsDeleter.cs
> +        public Dictionary<string, int> DeleteBoringWords(Dictionary<string, int> words)
Зачем тут знать про кол-во слов? Скучные слова - это про содержание, а не количество

2022-12-11 16:19 UTC, massshasch commented on TagsCloudContainer/BoringWordsDeleter.cs
> +        public Dictionary<string, int> DeleteBoringWords(Dictionary<string, int> words)
\+

2022-12-11 16:19 UTC, massshasch commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
\+

2022-12-11 16:21 UTC, massshasch commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
\+

2022-12-11 16:21 UTC, massshasch commented on TagsCloudContainer/LayouterAlgorithms/CircularCloudLayouter.cs
> +        public Dictionary<Tuple<string, int>, Rectangle> GetWordRectangleDictionary()
\+

2022-12-11 16:21 UTC, massshasch commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            foreach (var pair in words)
\+

2022-12-11 16:22 UTC, massshasch commented on TagsCloudContainer/Tests/RectangleCoordinatesCalculatorTests.cs
> +/*using System;
\+

2022-12-11 16:22 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +            for (int i = 0; i < WordsCount; i++)
\+

2022-12-11 16:22 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +        private Dictionary<string, int> MakeWordsFrequencyDictionary(string[] words)
\+

2022-12-11 16:49 UTC, massshasch commented on TagsCloudContainer/CoefficientCalculator.cs
> +    public class CoefficientCalculator
\+

2022-12-11 16:52 UTC, massshasch commented on TagsCloudContainer/CicularCloudDrawer.cs
> +    public class CircularCloudDrawer
\+

2022-12-11 16:52 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +            StartColor = Color.FromName(settings.BrushColor);
\+

2022-12-11 16:53 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/DefaultStainer.cs
> +        public DefaultStainer(InputFileHandler handler, CustomSettings settings)
\+

2022-12-11 16:53 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +            var builder = new ContainerBuilder();
\+

2022-12-11 16:54 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +            builder.RegisterType<TxtOpener>().As<IFileOpener>();
\+

2022-12-11 16:56 UTC, massshasch commented on TagsCloudContainer/FileSavers/IFileSaver.cs
> +        public void SaveCanvas();
\+

2022-12-11 16:56 UTC, massshasch commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        public string OpenFile() => File.ReadAllText(FilePath);
\+

2022-12-11 16:59 UTC, massshasch commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        private string FilePath { get; }
\+\+

2022-12-11 16:59 UTC, massshasch commented on TagsCloudContainer/FileOpeners/TxtOpener.cs
> +        public TxtOpener(CustomSettings settings) => FilePath = settings.PathToOpen;
\+

2022-12-11 17:00 UTC, massshasch commented on TagsCloudContainer/ConsoleUI.cs
> +        [Option("brushcolor", Required = false, Default = "Blue", HelpText = "Brush color")]
\+

2022-12-11 17:00 UTC, massshasch commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            var res = new Dictionary<string, int>();
\+

2022-12-11 17:05 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +            return input.Split(new[] {'\n', ' '});
\+

2022-12-11 17:12 UTC, massshasch commented on TagsCloudContainer/FileSavers/PNGSaver.cs
> +        public void SaveCanvas() => Canvas.Save(Path, new ImageFormat(ImageFormat.Png.Guid));
\+

2022-12-11 18:35 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +            builder.RegisterInstance(new CustomSettings(parsedArguments.FontName,
\+

2022-12-16 06:55 UTC, HELLoWorlD01100 requested changes

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagCloud/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
Это зачем?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +    public class InputFileHandler
Сейчас так выходит, что мы завязаны на источник получения слов. А если я хочу слова с сервера подтягивать?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +                throw new ArgumentException("Empty file");
А это исключительная ситуация? Просто отрисуем пустой Bitmap

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +            return frequencyDict;
Сокращения - плохо

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/InputFileHandler.cs
> +        private Dictionary<string, int> MakeWordsFrequencyDictionary(IEnumerable<string> words)
А может перепишем метод на LINQ? Упростим код

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/UI/ConsoleUi.cs
> +    public class ConsoleUi : IUi
Это не UI. ConsoleUI - это вот прям само окошечко консоли. У тебя в классе описаны настройки для ConsoleUI - аргументы командной строки.

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/WordsColoringAlgorithms/IWordsPainter.cs
> +        public Color[] GetColorsSequence(Dictionary<string, int> frequencyDictionary, string startColor);
А что нам мешает сразу передать нужный цвет? + если цвета с таким именем нету, то будет отложенное исключение =(

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/WordsColoringAlgorithms/GradientWordsPainter.cs
> +                throw new ArgumentException("Unknown brush color");
Dry: во всех реализациях интерфейса будет одно и то же. 
\+ Пользователю будет выводиться исключение со всеми подробностями вроде стэк трейса.

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/BoringWordsDeleter.cs
> +    public static class BoringWordsDeleter
А если я начинаю считать скучными словами не исходя из длины, а исходя из части речи?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            return words.Where(word => word.Length > 3).ToArray();
Почему не можем просто вернуть IEnumerable?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var graphics = Graphics.FromImage(canvas);
![image](https://user-images.githubusercontent.com/54909098/208038174-62adfd4d-1bed-4304-ba68-ed64b0813d80.png)
Обрати внимание на IDisposable

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            ICloudLayouterAlgorithm layouter)
Смотри, у нас есть алгоритм раскладки. По факту он просто возвращает прямоугольники. Нам правда важно, какая итоговая форма будет?
К чему это всё: как мне поменять алгоритм раскладки слов?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            int coefficient,
Эта штука берется исходя из настроек. Настройки у нас есть, зачем это снаружи считать?

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +        private static void RegisterFileSaverDependency(ContainerBuilder builder, string formatToSave)
Ок, а с Gui что будет? Какая из реализаций будет скрываться под IFileSaver? В Gui у нас не будет перезапускаться вся программа каждый раз.
Посмотри в сторону фабрики

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +            builder.RegisterType<Spiral>().AsSelf();
Дублирование

2022-12-16 06:55 UTC, HELLoWorlD01100 commented on TagsCloudContainer/Program.cs
> +            if (format == "txt")
То же самое, что и IFileSaver

2022-12-18 07:24 UTC, massshasch commented on TagCloud/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
+

2022-12-18 07:25 UTC, massshasch commented on TagCloud/Program.cs
> +﻿// See https://aka.ms/new-console-template for more information
/+

2022-12-18 07:45 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +    public class InputFileHandler
\+

2022-12-18 07:52 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +                throw new ArgumentException("Empty file");
\+

2022-12-18 07:52 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +            return frequencyDict;
\+

2022-12-18 08:10 UTC, massshasch commented on TagsCloudContainer/UI/ConsoleUi.cs
> +    public class ConsoleUi : IUi
\+

2022-12-18 08:19 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/IWordsPainter.cs
> +        public Color[] GetColorsSequence(Dictionary<string, int> frequencyDictionary, string startColor);
\+

2022-12-18 09:21 UTC, massshasch commented on TagsCloudContainer/BoringWordsDeleter.cs
> +            return words.Where(word => word.Length > 3).ToArray();
\+

2022-12-18 10:03 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var graphics = Graphics.FromImage(canvas);
\+

2022-12-18 10:23 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/IWordsPainter.cs
> +        public Color[] GetColorsSequence(Dictionary<string, int> frequencyDictionary, string startColor);
\+

2022-12-18 10:25 UTC, massshasch commented on TagsCloudContainer/BoringWordsDeleter.cs
> +    public static class BoringWordsDeleter
\+

2022-12-18 13:10 UTC, massshasch commented on TagsCloudContainer/InputFileHandler.cs
> +        private Dictionary<string, int> MakeWordsFrequencyDictionary(IEnumerable<string> words)
\+

2022-12-19 07:06 UTC, massshasch commented on TagsCloudContainer/WordsColoringAlgorithms/GradientWordsPainter.cs
> +                throw new ArgumentException("Unknown brush color");
\+

2022-12-19 08:36 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            int coefficient,
\+

2022-12-19 08:36 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +            builder.RegisterType<Spiral>().AsSelf();
\+

2022-12-19 19:55 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +        private static void RegisterFileSaverDependency(ContainerBuilder builder, string formatToSave)
\+

2022-12-19 19:55 UTC, massshasch commented on TagsCloudContainer/Program.cs
> +            if (format == "txt")
\+

2022-12-20 07:14 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            ICloudLayouterAlgorithm layouter)
\+

2022-12-22 12:37 UTC, HELLoWorlD01100 requested changes
1. "На этапе предобработки, приведи все слова к нижнему регистру и исключи скучные слова" - не выполнено.
2. Не выводится куда был сохранен файл.
3. Программа не запускается при использовании твоей dll. Из-за этого я не могу проверить доп. требования полностью.

2022-12-22 12:37 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var color = GetColorFromString(settings.BackGroundColor);
Было бы прикольно в одном месте собрать все приведения типов из настроек в нужны для приложения.
Сейчас получается так, что по всей программе разбросаны подобные приведения типов и исключение возникает где то в глубине программы, хотя мы могли это проверить сразу. Будет странно, если допустим твоя программа работает 3 минуты, а потом выкидывает исключение из-за того, что изначальные настройки ввели неправильно.

2022-12-22 12:37 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +                var rectangleHeight = wordCount * coefficient * word.Length + coefficient;
Дублирование кода из метода PlaceNextWord

2022-12-22 12:37 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var brushColors = painter.GetColorsSequence(frequencyDictionary, GetColorFromString(settings.BrushColor));
Слабая связь между словами и соотв. цветами. А что если метод GetColorsSequence вернет меньше на 1 цвет?

2022-12-22 12:37 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var brushColors = painter.GetColorsSequence(frequencyDictionary, GetColorFromString(settings.BrushColor));
Из-за этого тебе кстати приходится использовать counter. Вот если бы метод возвращал сразу всю нужную информацию...

2022-12-22 12:37 UTC, HELLoWorlD01100 commented on TagsCloudContainer/CircularCloudDrawer.cs
> +        public static void DrawWords(
Зачем нам иметь отдельный класс под CircularCloudAlgorithm? Можно передать алгоритм раскладки сюда, нам не важна форма, в которой будут разложены слова. В твоем случае мне под каждый алгоритм нужно будет добавлять новый класс Drawer, который будет дублировать логику CloudDrawer

2022-12-22 12:43 UTC, HELLoWorlD01100 commented on TagsCloudContainer/LayouterAlgorithms/LayouterFactory.cs
> +        public ICloudLayouterAlgorithm Create(Spiral spiral)
Spiral относится только к CircularCloudLayourter, зачем нам передавать ее, если я хочу алгоритм раскладки в прямоугольник?

2022-12-23 16:46 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var color = GetColorFromString(settings.BackGroundColor);
+

2022-12-23 18:08 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +                var rectangleHeight = wordCount * coefficient * word.Length + coefficient;
\+

2022-12-23 18:22 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +            var brushColors = painter.GetColorsSequence(frequencyDictionary, GetColorFromString(settings.BrushColor));
\+

2022-12-23 18:32 UTC, massshasch commented on TagsCloudContainer/LayouterAlgorithms/LayouterFactory.cs
> +        public ICloudLayouterAlgorithm Create(Spiral spiral)
\+

2022-12-23 19:06 UTC, massshasch commented on TagsCloudContainer/CircularCloudDrawer.cs
> +        public static void DrawWords(
\+

2023-11-23 04:57 UTC, closed without merging