TagsCloudContainer rshikhov
kontur-csharper/di pull request #181
Opened 2022-12-09 09:54 UTC by Hrenaki

Шихов Роман
Наставник: @coffee-and-problems

2022-12-13 14:12 UTC, coffee-and-problems requested changes

2022-12-13 14:12 UTC, coffee-and-problems commented on di.sln
> +	EndGlobalSection
тут почему-то из билда исключены проекты TagsCloudContainer.GUI и TagsCloudContainer.ConsoleApp

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer/Infrastructure/WordColorProviders/IWordColorProvider.cs
> +namespace TagsCloudContainer.Infrastructure
Здесь и во многих классах ниже неправильные неймспейсы - тут должно быть TagsCloudContainer.Infrastructure.WordColorProviders. Можно нажать правой кнопкой на папке и выбрать "Refactor this", потом "Adjust namespaces", чтобы поправить неймспейсы сразу во всей папке

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/TagsCloudGeneratorTests.cs
> +    internal class TagsCloudGenerator_Should
Странно, что класс и файл этого класса называются по-разному

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/TagsCloudGeneratorTests.cs
> +
А где тесты?)

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/WordPreparerTests.cs
> +    internal class WordPreparer_Should
Тут тоже класс и файл называются по-разному. И подчеркивание в названии класса обычно опускают

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/TextFileReaderTests.cs
> +namespace TagsCloudContainer.Tests.TextFileReaderTests
В этом проекте тоже немного уехали неймспейсы

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/CircularWordLayoutBuilderTests.cs
> +            var center = Point.Empty;
эти переменные не используются

2022-12-13 14:12 UTC, coffee-and-problems commented on TagsCloudContainer/Infrastructure/WordFontSizeProviders/Factories/WordConstFontSizeProviderFactory.cs
> +    public class WordConstFontSizeProviderFactory : IWordFontSizeProviderFactory
Странно выделять фабрику, если уже есть провайдер. Какую ценность несет выделение отдельной фабрики?

2022-12-13 19:21 UTC, Hrenaki commented on TagsCloudContainer/Infrastructure/WordColorProviders/IWordColorProvider.cs
> +namespace TagsCloudContainer.Infrastructure
Я это сделал намеренно: хотел, чтобы все базовые интерфейсы/реализации были в одном неймспейсе (кроме сеттингов, они все-таки более специфичные).
Но скидывать все файлы в одну папку не хотелось, поэтому раскидал их по соответствующим папкам, но без изменения нейспейса

2022-12-13 19:23 UTC, Hrenaki commented on TagsCloudContainer.Tests/TagsCloudGeneratorTests.cs
> +
Я хотел добавить тесты, но не придумал нормальный способ проверки результата, поэтому этот файл и остался без тестов

2022-12-13 19:53 UTC, Hrenaki commented on TagsCloudContainer/Infrastructure/WordFontSizeProviders/Factories/WordConstFontSizeProviderFactory.cs
> +    public class WordConstFontSizeProviderFactory : IWordFontSizeProviderFactory
Проблема в том, что часть сеттингов для провайдера формируется во время выполнения программы (словарь частот вхождения слов в вычитанный текст): поэтому потребовалась фабрика, которая создает провайдер с досформированными сеттингами.
Также в моем понимании сеттинги - это нечто одноразовое, объект, который передается для конфигурирования другого: поэтому вариант с использованием одного экземпляра сеттингов на всем протяжении выполнения программы сразу отпадает.
Фабрика дает возможность управлять моментом создания провайдера

2022-12-14 07:38 UTC, coffee-and-problems commented on TagsCloudContainer/Infrastructure/WordColorProviders/IWordColorProvider.cs
> +namespace TagsCloudContainer.Infrastructure
Неймспейсы - по сути те же папки, они нужны для логического разбиения кода на группы. Поэтому у шарпа есть договоренность, что неймспейс должен соответствовать пути до файла

2022-12-14 08:20 UTC, coffee-and-problems requested changes

2022-12-14 08:20 UTC, coffee-and-problems commented on TagsCloudContainer.Tests/TextFileReaderTests.cs
> +    internal class TextFileReaderShould
С подчеркиванием ок, но все еще по-разному называется файл и класс с тестами. Ты вроде придерживаешься конвенции наименования через Should (судя по названиям тестов ниже), поэтому давай все в одном стиле сделаем и переименуем файл в TextFileReaderShould

2022-12-14 08:20 UTC, coffee-and-problems commented on TagsCloudContainer/OpenNLPPOSFacade.cs
> +            using var modelIn = new java.io.FileInputStream(Path.Combine(binFolder, "en-pos-maxent.bin"));
java О_о

2022-12-14 08:20 UTC, coffee-and-problems commented on TagsCloudContainer/OpenNLPPOSFacade.cs
> +            openNLPTagToWordTypeDictionary.Add(wordTagger.tag(new[] { "animal" })[0], WordType.Noun);
Разве у этой библиотеки нет словаря из коробки? Его тут надо вручную строить со всеми известными словами? Если это правда так, то это очень неподдерживаемое решение - лучше просто захардкодить хэшсет "скучных слов" и каждое слово проверять на нахождение в этом черном списке. Это уже более жизнеспособно будет.
UPD: Судя по тестам, все таки оно само умеет определять часть речи слова. Зачем тогда эти добавления? Что происходит)

2022-12-14 08:38 UTC, Hrenaki commented on TagsCloudContainer/OpenNLPPOSFacade.cs
> +            openNLPTagToWordTypeDictionary.Add(wordTagger.tag(new[] { "animal" })[0], WordType.Noun);
почему-то OpenNLP возвращает POS тег строкой, а не значением из enum'а - для удобства мне пришлось сделать свой enum, брать по примеру части речи, получать строковый тег и класть в словарь с соответствующим значением enum'а.
На офф сайте конечно есть словарь тегов для частей речи, но почему-то он неправильный: для существительного по факту возвращается тег 'NOUN', а на офф сайте указан 'NN'. Для других частей речи такая же фигня

2023-11-23 04:57 UTC, closed without merging