Ясиновский Александр
kontur-csharper/di pull request #183
Opened 2022-12-11 04:19 UTC by Alex2021cyberhuman

Привет, @bannikovilea.
Я решил переписать заново, вот что вышло. Не знаю какие тесты нужно написать?

2022-12-11 04:28 UTC, Alex2021cyberhuman commented
![2tlrdzwv 1nx](https://user-images.githubusercontent.com/59359082/206886240-26792c3a-a772-44a6-afb4-db7b2efb2d61.png)
![hreoibj5 qc4](https://user-images.githubusercontent.com/59359082/206886460-0fd075ae-b56c-43fe-b624-5629d3822613.png)

2022-12-14 09:24 UTC, bannikovilea requested changes

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Cli/JsonSettingsFactory.cs
> +        throw new NotImplementedException();
Именно NotImplementedException хотим кидать? Кажется, что метод реализован, и эксепшен связан с тем, что мы по каким-то внутренним причинам не выбрали цвет

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Cli/Program.cs
> +        container.Register<MorphAnalyzer>(Reuse.Singleton);
Предполагаю, что можно поиграться с конвенциями контейнера и добавить опцию, чтобы все регистрировалось по дефолту как синглтон

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Cli/Program.cs
> +        container.Register<MorphAnalyzer>(Reuse.Singleton);
Давай вынесем конфигурацию контейнера в отдельный метод

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Cli/tag-cloud-settings.json
> +    "BasePath": "C:\\Users\\Admin\\repositories\\alex2021cyberhuman\\di\\TagsCloudContainer\\TagsCloudContainer.Cli\\bin\\Debug\\net7.0-windows\\images"
Предлагаю тут использовать относительный путь. Чтобы другим, кто будет использовать и смотреть твой код не приходилось в этом разбираться)

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Gui/App.xaml.cs
> +        container.Register<MorphAnalyzer>(Reuse.Singleton);
Кажется код дублируется между .Cli и Gui. Лучше перенести в отдельный метод или экстеншн, который будет конфигурить контейнер. Раз конфигурация одинаковая, этот метод может жить рядом с библиотечными классами. А тут дорегивать дополнительно, только необходимое для конкретного проекта

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Gui/BrushConverter.cs
> +        var match = RgbRegex().Match(stringValue);
Расскажи, почему регех пересоздается для каждого случая? Чем плох просто статичный?

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Gui/BrushConverter.cs
> +        var match = RgbRegex().Match(stringValue);
Посмотрел, это свежее из нет7. Но всё равно интересно чем ты руководствовался, когда выбирал)

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer/ClassicDrawer.cs
> +    private IEnumerable<(string word, Font font, Rectangle rectangle)> GetTagPropertyItems(
Очень плотно смотрится `IEnumerable<(string word, Font font, Rectangle rectangle)>` давай вынесем лучше в класс эту штуку `(string word, Font font, Rectangle rectangle)`

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer/EnumerableExtensions.cs
> +    public static void Foreach<T>(this IEnumerable<T> enumerable, Action<T, int> action)
по сигнатуре и названию метода не очевидно, что будет передан счетчик

2022-12-14 09:24 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer/RandomColoredDrawer.cs
> +public class RandomColoredDrawer : IDrawer
Давай сделаем под каждый класс отдельный файлик

2022-12-14 09:30 UTC, Alex2021cyberhuman commented on TagsCloudContainer/TagsCloudContainer.Gui/BrushConverter.cs
> +        var match = RgbRegex().Match(stringValue);
Там синглтон внутри.

2022-12-14 09:50 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Cli/JsonSettingsFactory.cs
> +            var regex = new Regex(@"#(?<r>\d{1,2})#(?<g>\d{1,2})#(?<b>\d{1,2})(#(?<a>\d{1,2}))?");
А почему тут такой регекс, а не нет7 регекс?

2022-12-15 02:38 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer.Core/TagsCloudContainer.Core.csproj
> +        <TargetFramework>net7.0</TargetFramework>
Для библиотечных проектов можно заряжать netstandard2.0 или 2.1 так будет обеспечиваться поддержка более старых версий фреймворка. Так, совет на будущее)

2022-12-15 02:41 UTC, bannikovilea commented on TagsCloudContainer/TagsCloudContainer/ContainerHelper.cs
> +    public static Container RegisterDefaultSingletonContainer()
Если в нескольких местах когда позвать метод получения контейнера. У нас же будет два контейнера. В данной задаче ничего страшного не произойдет, но на каждый вызов метода будет создаваться новый контейнер. Там где нужен честный единственный синглтон на всю приложуху лучше контейнер складывать в статическое поле. Так благодаря ленивости и синглтонности статики у тебя будет контейнер, который один на всю прилагу

2023-11-23 04:57 UTC, closed without merging