Заколюкин Степан
kontur-csharper/di pull request #212
Opened 2024-12-19 11:10 UTC by StepanZakolukin

2024-12-23 15:55 UTC, w1jtoo approved these changes
Сейчас много всего не хватает:

1. Основная часть задания --- наличие интерфейсов и композиция их в DI. Их сильно не хватает
2. Нет тестов на каждый из модулей
3. Не хватает итогового проекта в котором будет либо приложулька с GUI/CLI
4. \* видел помарки/опечатки. Старайся проверять их до отправки на проверку. Чтобы экономить и твоё и моё время.

2024-12-23 15:55 UTC, w1jtoo commented on TagCloud.Console/Program.cs
> +internal class Program
А почему тут постой файл. Ещё не доделал или забыл пушнуть?

2024-12-23 15:55 UTC, w1jtoo commented on TagCloud.Tests/CircularCloudTests.cs
> +namespace TagCloud.Tests;
Тестов явно мало. 

1. Тесты на алгоритм проверялись в предыдущей части домашки
2. Ожидаю, что у тебя будут тесты на все остальные абстракции, которые у тебя есть в проекте

2024-12-23 15:55 UTC, w1jtoo commented on TagCloud.Tests/VisualizationCloudLayout.cs
> +namespace TagCloud.Tests;
Странновато. По логике вещей эта штука должна относиться к основному проекту

\+ её нужно спрятать за абстракцией

2025-01-03 16:19 UTC, w1jtoo requested changes
По требованиям всё гуд:

1. Доп. требования. Я в коде нашел только_Предобработка слов_, Что ты сделал хорошо, но нужно домазать тестами. Нужно ещё что-то, чтобы был +1 балл на допы. Напиши, что планировал/будешь делать

2. Базовые требования. Неплохо. Нужны тесты и исправления по работе с зависимостями (то, что вокруг конструкторов часто). Из мелочи, у тебя нельзя выбрать цвет 💀 Но можем закрыть на это глаза

2025-01-03 16:19 UTC, w1jtoo commented on di.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TagCloud.Tests", "TagCloud.Tests\TagCloud.Tests.csproj", "{9A2F412F-B70F-4431-81CD-79BD6BA5B16C}"
В `.sln` нету `TagCloud.Console`

Большинство IDE не увидят этот проект и будут правы :)

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.Console/Program.cs
> +        var path = "C:/Users/stepa/Desktop/Mystem/in.txt";
Не будет работать у меня. Ненадотак

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/CloudLayout/Point.cs
> +public class Point(int x, int y)
Оч странная конструкция и структура данных.

По логике это должна быть неизменяемая часть данных (потому что повторений очень мало, а те что есть проще создавать заново, чем работать с ссылками).

И тут есть два варианта:
1. `record` он идеально подходит по логике и скорее всего сделает код чуточку оптимальнее
2. `class` простой и понятный, но в твоём случае непонятно зачем ему приватные x, y, которые при том можно менять

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/ImageGeneration/IVisualizationProvider.cs
> +    public float CloudCompressionRatio { get; set; }
Смотри, у тебя сейчас (и в некоторых других местах так же) настройки/данные лежат в интерфейсах. У этого подхода есть несколько минусов:

1. Сложно тестировать -- нельзя проверить часть с настройками, нужно это делать тестируя весь провайдер
2. Провоцирует к ошибкам. Во первых, во всех случаях когда нужно будет писать свою реализацию провайдера нужно будет копипастить код с настройками; во вторых, в коде можно поменять настройки во время генерации фотки 🤯 

Старайся всегда растаскивать интерфейсы и DTОшки отдельно. Одно про логику, второе про хранение данных и _иногда_ их валидацию.

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/ImageGeneration/VisualizationCloudLayout.cs
> +        WordsInfo = words;
Тут тоже проблема с конструктором.

Он у тебя прям в методе. Зачем вне этого метода знать об зависимостях? Либо только внутри, либо везде. Классический вариант с DI -- передать зависимости в конструктор (это часть твоего задания)


Даже IDE поругивается что что-то идёт не так:

```
C:\Users\kharlov.v\dev\di\TagCloud\ImageGeneration\VisualizationCloudLayout.cs(12,12): warning CS8618: свойство "ColorPicker", не допускающий значения NULL, должен содержать значение, отличное от NULL, при выходе из конструктор
а. Возможно, стоит объявить свойство как допускающий значения NULL. [C:\Users\kharlov.v\dev\di\TagCloud\TagCloud.csproj]
```

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/TextProcessing/WordInfo.cs
> +        if (!partsOfSpeech.Contains(partOfSpeach))
Кажется, фича с предобработкой слов должна быть по настройке. Потому что я уверен, что половину слов не получится переварить адекватно из не литературных текстов. Если ему дать слово "лол", оно уже его за Лолу считает. Про "кек" молчу)

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/TextProcessing/TextPreprocessing.cs
> +        return File.ReadAllLines(outputFile);
NIT: твой алгоритм не сильно то завязан на длину текста. Только на уникальное кол-во слов. Как пример, я взял 100 Онегиных из тестов и программа умерла. А если взять 2к, то вообще по памяти умрёт :)

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.GUI/Program.cs
> +        services.AddScoped<Point>(_ => new Point(imageSize.Width / 2, imageSize.Height / 2));
Тут же не любая точка должна быть такой. А только наша конкретная🤔

Подумай, как сделать так, чтобы только в одном конструкторе была такая точка.

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.GUI/Controls/MyButton.cs
> +public class MyButton : Button
Плохое название) TagCloudButton

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.GUI/Controls/PushButtonPanel.cs
> +}
NIT: кажется, логически эти два шага можно разделить, но с точки зрения работы в UI это странно. Можно схлопнуть в один шаг

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud/TextProcessing/TextPreprocessing.cs
> +        File.Create(outputFile).Close();
А можно обойтись без файлов? Хороший код не портит окружение и ломается, если окружение испорчено

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.Tests/CircularCloudTests.cs
> +namespace TagCloud.Tests;
UP

Тестов маловато:

1. Можно посмотреть на то, как `TextPreprocessing` должен вести себя в зависимости от состояния файла с словами (поломан, его нету, пустой и т.п.)
2. Можно потестить части речи (WordInfo)
3. Нужно побольше функциональных тестов, которые сделают всё от начала до конца в программе

2025-01-03 16:19 UTC, w1jtoo commented on TagCloud.Tests/VisualizationCloudLayout.cs
> +namespace TagCloud.Tests;
Щас норм

2025-01-03 16:19 UTC, w1jtoo commented on di.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TagCloud.Tests", "TagCloud.Tests\TagCloud.Tests.csproj", "{9A2F412F-B70F-4431-81CD-79BD6BA5B16C}"
Удалить нельзя оставить

2025-01-03 16:20 UTC, w1jtoo commented on TagCloud.Console/Program.cs
> +internal class Program
Щас норм

2025-01-04 06:56 UTC, StepanZakolukin commented on di.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TagCloud.Tests", "TagCloud.Tests\TagCloud.Tests.csproj", "{9A2F412F-B70F-4431-81CD-79BD6BA5B16C}"
Исправил

2025-01-04 07:17 UTC, StepanZakolukin commented on di.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TagCloud.Tests", "TagCloud.Tests\TagCloud.Tests.csproj", "{9A2F412F-B70F-4431-81CD-79BD6BA5B16C}"
Я изначально создавал этот проект, чтобы было проще тестить как работает проект TagCloud и на случай если бы решил делать консольную реализацию. Но в итоге решил делать только GUI, поэтому и удалил. Наверное мне стоило добавить этот проект в gitignore, чтобы не засорять историю git

2025-01-04 07:31 UTC, StepanZakolukin commented on TagCloud/CloudLayout/Point.cs
> +public class Point(int x, int y)
Исправил, сделал Point record-ом

2025-01-04 09:21 UTC, StepanZakolukin commented on TagCloud.GUI/Controls/PushButtonPanel.cs
> +}
Поправил, теперь одна кнопка отвечает за генерацию и сохранение

2025-01-04 11:43 UTC, StepanZakolukin commented on TagCloud/TextProcessing/TextPreprocessing.cs
> +        File.Create(outputFile).Close();
Исправил. Сделал так, чтобы текст из mystem записывался в стандартный поток, а затем считывался из него построчно в методе ParseText

2025-01-04 11:56 UTC, StepanZakolukin commented on TagCloud/TextProcessing/TextPreprocessing.cs
> +        return File.ReadAllLines(outputFile);
Исправил построчным чтением строк из потока

2025-01-04 12:01 UTC, StepanZakolukin commented on TagCloud.GUI/Controls/MyButton.cs
> +public class MyButton : Button
Переименовал название этого класса и еще нескольких с подобными названиями

2025-01-05 08:51 UTC, StepanZakolukin commented on TagCloud/ImageGeneration/VisualizationCloudLayout.cs
> +        WordsInfo = words;
Исправил, пробросил зависимости в конструктор

2025-01-05 08:52 UTC, StepanZakolukin commented on TagCloud.GUI/Program.cs
> +        services.AddScoped<Point>(_ => new Point(imageSize.Width / 2, imageSize.Height / 2));
Исправил такой конструкцией:
`services.AddTransient<ILayoutProvider>(_ => new CircularCloud(new Point(imageSize.Width / 2, imageSize.Height / 2)));`

2025-01-05 17:06 UTC, StepanZakolukin commented on TagCloud/TextProcessing/WordInfo.cs
> +        if (!partsOfSpeech.Contains(partOfSpeach))
Исправил, добавил возможность выбрать структуру содержания файла

2025-01-05 18:10 UTC, StepanZakolukin commented on TagCloud/ImageGeneration/IVisualizationProvider.cs
> +    public float CloudCompressionRatio { get; set; }
Исправил

2025-01-07 07:26 UTC, StepanZakolukin commented on TagCloud.Tests/CircularCloudTests.cs
> +namespace TagCloud.Tests;
Исправил

2025-01-19 11:19 UTC, w1jtoo requested changes

2025-01-19 11:19 UTC, w1jtoo commented on TagCloud.Tests/WordInfoTests.cs
> +        var incorrectPartsOfSpeech = new[] { "0", "999", "a", word, "причастие", "деепричастие", "слово" };
Старайся выносить такое в `[TestCase(...)]` так, если тест упадёт на одном из вводов, будет хороший вывод => будет понятно почему тест свалился

2025-01-19 11:19 UTC, w1jtoo commented on TagCloud.Tests/TxtReaderTests.cs
> +        random.Shuffle(lines);
Тут копипаста. По хорошему бы вытащить её. Так будет проще рефакторить и ревьюить

2025-01-19 11:19 UTC, w1jtoo commented on TagCloud.Tests/VisualizationCloudLayoutTests.cs
> +        var services = new ServiceCollection();
Старайся делать так, чтобы конструктор был тупой как пробка. Это неявная общая договоренность. Что-то сложное в отдельном методе.

Конкретно в этом месте уместно будет использовать `[SetUp]`. Этот атрибут отмечает методы, которые будут вызываться перед каждым тестом. За счет это очень удобно формировать "окружение" для каждого теста

2025-01-19 11:19 UTC, w1jtoo commented on di.sln
> +Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "TagCloud.Tests", "TagCloud.Tests\TagCloud.Tests.csproj", "{9A2F412F-B70F-4431-81CD-79BD6BA5B16C}"
Всё таки не удалил?

2025-01-19 11:19 UTC, w1jtoo commented on TagCloud/TextProcessing/WordInfo.cs
> +        if (!partsOfSpeech.Contains(partOfSpeach))
Тут зачту. Но по логике тебе стоило вытащить это в абстракции, так, чтобы `PerformProcessing` вообще ничего не знал про `ContentStructure.Literary`

2025-01-19 11:19 UTC, w1jtoo commented on TagCloud/ImageGeneration/IUserInputProvider.cs
> +public interface IUserInputProvider
Тут аналогично настройкам же. Этот класс - контейнер. В нём по факту лежит состояние ввода пользователя. Маловероятно, что придётся изменять логику этого файла (наследоваться от этого интерфейса). 

Поэтому наличие интерфейса лишнее

2025-01-29 07:07 UTC, closed without merging