Беляев Илья
kontur-csharper/di pull request #91
Opened 2020-11-28 20:21 UTC by CaptainBelyash

@fng3r

2020-11-29 11:39 UTC, fng3r requested changes

2020-11-29 11:39 UTC, fng3r commented on TagCloud/DataReaders/IDataReader.cs
> +        public List<string> ReadWords(string filePath);
это до сих пор абстракция для чтения из файла, смена  названия ее суть никак не изменила, ты до сих пор в публичном интерфейсе выставляешь наружу путь до файла

2020-11-29 11:39 UTC, fng3r commented on TagCloud/DataReaders/TextFileReader.cs
> +            return words;
это все можно заменить одной строчкой
https://docs.microsoft.com/en-us/dotnet/api/system.io.file.readlines?view=net-5.0

2020-11-29 11:39 UTC, fng3r commented on TagCloud/DataReaders/IDataReader.cs
> +        public List<string> ReadWords(string filePath);
почему он, кстати, называется `IDataReader`? data - слишком общее название, а у тебя здесь достаточно конкретная вещь - список слов

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/ITagCloudDrawer.cs
> +        public void DrawTagCloud(HashSet<TagInfo> tags);
не следует требовать от клиента (того, кто будет этот метод вызывать) настолько конкретный тип, если даже тебе внутри реализации нужен именно хэшсет, то это преобразование ты можешь сделать сам, тут будет достаточно `IReadOnlyCollection`

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/IPicture.cs
> +    }
очень сомнительная абстракция, для чего она нужна?
в ней намешаны 2 ответственности сейчас: визуализация и сохранение в файл

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/IPicture.cs
> +    }
и вообще - нужна ли эта пачка методов? наверняка ведь это все в конечно счете используется в сценарии "нарисуй тег", может, тогда, в интерфейсе стоит только это и оставить?

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/Picture.cs
> +        }
давай ты будешь либо использовать его, либо выпилишь, тем более, что он торчит в интерфейсе

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TagInfo.cs
> +        public readonly Font Font;
в тег-таки просочилась инфа о том, как он должен отрисовываться, нужно исправить
мало того, что просто просочилась эта информация, так ты теперь тут еще и используешь примитив из либы для рисования

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/Picture.cs
> +            SetBrushColor(color);
зачем ты переиспользуешь одну и ту же кисть? создавай каждый раз новую
у тебя сейчас цвет меняется для рисования текущей фигуры, а потом не ресетится на старое значение к тому же

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/TagCloudDrawer.cs
> +            foreach (var tag in tags.OrderByDescending(t => t.Font.Height))
размер шрифта как раз здесь и следует определять

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/TagCloudDrawer.cs
> +        public TagCloudDrawer(IRectangleLayouter layouter, IPicture picture)
повторюсь, не понимаю, для чего нужен этот IPicture, там просто сгрппированы методы для визуализации облака, так почему бы им прямо тут и не жить в TagCloud**Drawer**? функции этой абстракции для меня пока неизвестны

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/TagCloudDrawer.cs
> +            var tagsToPosition = new Dictionary<TagInfo, Point>();
а почему бы сразу и не отрисовать? зачем их аккумулировать в этом словаре, если они затем сразу же отрисовываются?

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Drawers/TagCloudDrawer.cs
> +            picture.FillRectangle(new Rectangle(0, 0, 2000, 2000), Color.Black);
что это за магические размеры?

2020-11-29 11:39 UTC, fng3r commented on TagCloud/Layouters/CircularCloudLayouter.cs
> +        private List<Rectangle> rectangles;
wtf?

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TagCloud.cs
> +        public void MakeTagCloud(string path)
абстракция с чтением из файла протекает :(

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TagCloud.cs
> +        public void MakeTagCloud(string path)
по-хорошему, этот класс должен принимать уже готовый список тегов, как-то распологать его, а потом уже визуализировать, а вся логика по анализу текста должна уехать из этого класса
можно обсудить

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TagCloud.cs
> +        }
определение размера шрифта должно уехать в Drawer, а в тэге можно хранить информацию о его "удельном весе", то есть отношению количества появлений слова в тексте к общему кол-ву слов, и размер шрита уже должен определяться исходя из этой информации

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TextAnalyzer/StandardTextAnalyzer.cs
> +        public StandardAnalyzer(IWordNormalizer normalizer, HashSet<string> bannedWords = null)
фильтрацию сделать расширяемой, уже обсудили

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TextAnalyzer/StandardTextAnalyzer.cs
> +                this.bannedWords = bannedWords;
этот код выпилится, но тут следовало бы сделать так `this.bannedWords = bannedWords ?? new Hashset<string>(0)`, сейчас этот хэшсет создается без надобности

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TextAnalyzer/StandardTextAnalyzer.cs
> +            return wordCounts;
это все можно сильно упростить до
```
return words
    .Select(word => normalizer.Normalize(word)
    .Where(word => filters.All(filter.FilterWord))
    .GroupBy(word => word)
    .ToDictionary(group => group.Key, group => group.Count);
```

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TextAnalyzer/StandardTextAnalyzer.cs
> +            return wordCounts;
а на самом деле из анализатора стоит сразу возвращать список тегов

2020-11-29 11:39 UTC, fng3r commented on TagCloud/TextAnalyzer/WordNormalizer/WordNormalizer.cs
> +            return word.ToLower();
а в начальную форму приводить не нужно? или это доп. задание?

2020-12-03 15:03 UTC, fng3r requested changes

2020-12-03 15:03 UTC, fng3r commented on TagCloud/TextReaders/FileReader.cs
> +            return File.ReadLines(filePath).ToList();
кстати, он читает все строчки из файла, а не все слова, давай-ка сделаешь сплит по строчке

2020-12-03 15:03 UTC, fng3r commented on TagCloud/UserInterfaces/ConsoleUserInterface.cs
> +            var spiralStep = 0.005;
такие вещи можно будет унести в дефолтные значения параметров

2020-12-03 15:03 UTC, fng3r commented on TagCloud_Tests/Program.cs
> +namespace TagCloud_Tests
солидные тесты

2020-12-03 15:03 UTC, fng3r commented on TagCloud/Program.cs
> +        }
вот сюда куда-то нужно сохранение картинки унести

2020-12-04 11:35 UTC, fng3r requested changes

2020-12-04 11:35 UTC, fng3r commented on TagCloud/ImageSavers/ImageSaver.cs
> +        private string ext;
давай дашь полное название переменной, сокращение тут ни к чему

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Drawers/TagDrawer.cs
> +        private DrawerSettings settings;
сделай везде поля `readonly`, где они не изменяются

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Program.cs
> +            var cli = new ConsoleLineInterface(args);
cli = command **line** interface на самом деле

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Settings/DrawerSettings.cs
>          public Color BackgroundColor;
а почему это поля, а не свойства?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Settings/DrawerSettings.cs
> +            bool orderByWeight)
лучше выпилить конструктор и открыть сеттеры для свойств

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Settings/DrawerSettings.cs
> +            bool orderByWeight)
для классов с настройками в общем случае стоит так делать, наверное, всегда, учитывая то, что я не хочу указывать в настройках всю эту портянку, а только нужные, ожидая, что у остальных подставятся дефолтные значения

2020-12-04 11:35 UTC, fng3r commented on TagCloud/Settings/SaverSettings.cs
> +        public SaverSettings(string path, string fileName, string extention)
typo

2020-12-04 11:35 UTC, fng3r commented on TagCloud/TagCloud.cs
> +            drawer.Dispose();
почему это вдруг drawer должен задиспозиться после одного вызова этого метода? если я хочу не одно облако, а несколько?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/TagCloud.csproj
> +      <PackageReference Include="CommandLineParser" Version="2.9.0-preview1" />
превьюшные версии, как правило, нестабильные и используются для бета-тестирования, в проде их лучше не использовать, но это так, к слову

2020-12-04 11:35 UTC, fng3r commented on TagCloud/TextReaders/FileReader.cs
> +            return File.ReadAllLines(filePath).SelectMany(line => line.Split()).ToList();
здесь стоит еще указать `StringSplitOptions.RemoveEmptyEntries` (как-то так), чтобы мусор при сплите не получить

2020-12-04 11:35 UTC, fng3r commented on TagCloud/UserInterfaces/CLIArguments.cs
> +            Separator = ',', Default = new []{"Noun", "Verb", "Adjective", "Adverb", "Conjunction"})]
почему по умолчанию исключается все, а не наоборот?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/UserInterfaces/CLIArguments.cs
> +            Separator = ',', Default = new []{"Noun", "Verb", "Adjective", "Adverb", "Conjunction"})]
или это косяк после копипасты сообщения из предыдущего параметра?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/UserInterfaces/CLIArguments.cs
> +        public string OutputFileName { get; set; }
зачем это разделять на 2 параметра?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/UserInterfaces/CLIArguments.cs
> +        public string Extention { get; set; }
typo
в решарпере же есть ReSpeller, прогони-ка его

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordFilters/GramPartsFilter.cs
> +                        break;
а чо бы энамом не сделать часть речи? парсер энамы умеет из коробки обрабатывать, вроде. не нужно будет этот код писать, да и даже если пришлось бы, то место ему не тут, а в парсере

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordFilters/GramPartsFilter.cs
> +                        break;
а, стоп, у тебя же и так есть энам, тогда это еще более бессмысленным выглядит

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordFilters/GramPartsFilter.cs
> +        private Mysteam mysteam;
вроде как, он mystem называется. а не myste**a**m

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordsAnalyzer.cs
> +                    .Where(word => filters.All(f => !f.ShouldExclude(word)))
`!filter.Any(f => f.ShouldExclude(word))` яснее, как по мне, потому что одно отрицание применяемое ко всему выражению, воспринимается проще, чем набор оных, применяемых к каждому элементу (имными словами, "ни один фильтр не должен исключить слово" проще, чем "все фильтры должны НЕ исключить слово")
но это так, вкусовщина, в общем-то

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordsAnalyzer.cs
> +            return minValue != maxValue ? (double) (value - minValue) / (maxValue - minValue) : 1;
все тот же вопрос: если value = minValue, то у тега будет нулевой вес, как он будет отображаться при отрисовке (никак?)?

2020-12-04 11:35 UTC, fng3r commented on TagCloud/WordsAnalyzer/WordsAnalyzer.cs
> +}
давай картинки в отдельную папку, а то он засоряют корень проекта

2020-12-04 12:22 UTC, CaptainBelyash commented on TagCloud/WordsAnalyzer/WordsAnalyzer.cs
> +            return minValue != maxValue ? (double) (value - minValue) / (maxValue - minValue) : 1;
Нулевой вес тега соответствует минимальному размеру шрифта, наибольший вес - максимальному

2020-12-04 12:26 UTC, CaptainBelyash commented on TagCloud/WordsAnalyzer/WordFilters/GramPartsFilter.cs
> +        private Mysteam mysteam;
Похоже на то, что в библиотеке назвали именно Myste**a**m, отсылаясь на то, что библиотека работает с сторонним приложением

2020-12-04 12:51 UTC, CaptainBelyash commented on TagCloud/UserInterfaces/CLIArguments.cs
> +        public string OutputFileName { get; set; }
Чтобы явно указывать путь до места сохранения облака когда требуется

2020-12-04 14:04 UTC, CaptainBelyash commented on TagCloud/Settings/DrawerSettings.cs
> +            bool orderByWeight)
Сделал только для DrawerSettings, так как у остальных на данный момент не так много свойств

2022-11-01 05:48 UTC, closed without merging